-- 017 — SAP purchasing-group master (code -> description, HO vs UNIT).
--
-- v1 carries this map inline as a ~300-entry JS literal. The charts that need it
-- aggregate in SQL, so it lives in a table here rather than in TypeScript: a
-- chart can join it, and an administrator can correct a description without a
-- deployment.
--
-- `is_ho` is v1's rule, precomputed so "PO Issued By" is a plain GROUP BY: a
-- desk is Head Office when its code starts with '@', or its description starts
-- with "HO", or contains "HO-". Everything else is a site UNIT.
--
-- Descriptions are people's names in many cases (SAP uses the purchasing group
-- as the buyer's desk), which is why the charts built on this are labelled
-- "per PIC" in the business's own words.

CREATE TABLE IF NOT EXISTS core.dim_purch_group (
  code        text PRIMARY KEY,
  description text NOT NULL,
  is_ho       boolean NOT NULL
);

INSERT INTO core.dim_purch_group (code, description, is_ho) VALUES
  ('@01', 'HO-PCH-1', true),
  ('@02', 'HO-PCH-2', true),
  ('@03', 'HO-PCH-3', true),
  ('@04', 'DEVID', true),
  ('@05', 'Adm.Technical', true),
  ('@06', 'RM-ADM-1', true),
  ('@07', 'HO-CERT-1', true),
  ('@08', 'HO-CERT-2', true),
  ('@09', 'HO-HRGA-1', true),
  ('@10', 'Afrizal Chandra', true),
  ('@11', 'Admin Operational', true),
  ('@12', 'HO-LOG-1', true),
  ('@13', 'HO-PCH-6', true),
  ('@14', 'HO-PCH-7', true),
  ('@15', 'Admin MIS', true),
  ('@16', 'Risya', true),
  ('@17', 'HO-LOG-2', true),
  ('@18', 'HO-PCH-8', true),
  ('@19', 'Aldi Chandra', true),
  ('@20', 'Natasha S', true),
  ('@21', 'HO-PCH-7', true),
  ('@22', 'Jo Timothy', true),
  ('@23', 'HO-PCH-4', true),
  ('@24', 'HO-PCH-5', true),
  ('@25', 'DPA-Admin1', true),
  ('@26', 'DPA-Admin2', true),
  ('@27', 'Crewing-TugBarge', true),
  ('@28', 'Crewing-Tanker', true),
  ('@29', 'Crewing-Bulker', true),
  ('@30', 'Docking.Adm1', true),
  ('@31', 'Docking.Adm2', true),
  ('AG1', 'Gede Purwa Ryana', false),
  ('AG2', 'Dimas Praditya', false),
  ('AGX', 'ASGD-Export', false),
  ('BD1', 'HO-BDS LOCAL', true),
  ('BF1', 'HO-BFL LOG LOC', true),
  ('BK0', 'BKS-HRGA', false),
  ('BK1', 'BKS-NTRD Pur', false),
  ('BK2', 'BKS-NTRD Log', false),
  ('BK3', 'Bks-TRD Log Locl', false),
  ('BK4', 'Bks-TRD Log Exim', false),
  ('BL0', 'BLW-HRGA', false),
  ('BL1', 'BLW-NTRD Pur', false),
  ('BL2', 'BLW-NTRD Log', false),
  ('BL3', 'BLW-TRD Log Locl', false),
  ('BL4', 'BLW-TRD Log Exim', false),
  ('BM0', 'BTM-HRGA', false),
  ('BM1', 'BTM-NTRD Pur', false),
  ('BM2', 'BTM-NTRD Log', false),
  ('BM3', 'BTM-TRD Log Locl', false),
  ('BM4', 'BTM-TRD Log Exim', false),
  ('BP1', 'PURCHASING BTP', false),
  ('BT0', 'BTG-HRGA', false),
  ('BT1', 'BTG-NTRD Pur', false),
  ('BT2', 'BTG-NTRD Log', false),
  ('BT3', 'BTG-TRD Log Locl', false),
  ('BT4', 'BTG-TRD Log Exim', false),
  ('BY0', 'BYH-HRGA', false),
  ('BY1', 'BYH-NTRD Pur', false),
  ('BY2', 'BYH-NTRD Log', false),
  ('BY3', 'BYH-TRD Log Locl', false),
  ('BY4', 'BYH-TRD Log Exim', false),
  ('CL1', 'Store Unit TC', false),
  ('CL2', 'GAUnit TC', false),
  ('EB1', 'HO-EBD EXPORT', true),
  ('ER1', 'HO-ERP SAP', true),
  ('F1', 'HRGA MEDAN', false),
  ('F2', 'HRGA JAKARTA', false),
  ('F3', 'MEDAN PURCHASE TRD', false),
  ('F4', 'JKT PURCHASE TRADE', false),
  ('F5', 'MEDAN PUR NTRD', false),
  ('F6', 'JKT PURCHASE NTRD', false),
  ('HR1', 'NTRD-HO-HRGA-1', true),
  ('HR2', 'NTRD-HO-HRGA-2', true),
  ('HR3', 'NTRD-HO-HRGA-3', true),
  ('HR4', 'NTRD-HO-HRGA-4', true),
  ('IM1', 'NTRD-HO-Import-1', true),
  ('IM2', 'NTRD-HO-Import-2', true),
  ('JB0', 'JMB-HRGA', false),
  ('JB1', 'JMB-NTRD Pur', false),
  ('JB2', 'JMB-NTRD Log', false),
  ('JB3', 'JMB-TRD Log Locl', false),
  ('JB4', 'JMB-TRD Log Exim', false),
  ('KJ0', 'KJG-HRGA', false),
  ('KJ1', 'KJG-NTRD Pur', false),
  ('KJ2', 'KJG-NTRD Log', false),
  ('KJ3', 'KJG-TRD Log Locl', false),
  ('KJ4', 'KJG-TRD Log Exim', false),
  ('KL0', 'KLG-HRGA', false),
  ('KL1', 'KLG-NTRD Pur', false),
  ('KL2', 'KLG-NTRD Log', false),
  ('KL3', 'KLG-TRD Log Locl', false),
  ('KL4', 'KLG-TRD Log Exim', false),
  ('KM0', 'KMI-HRGA', false),
  ('KM1', 'KMI-NTRD Pur', false),
  ('KM2', 'KMI-NTRD Log', false),
  ('KM3', 'KMI-TRD Log Locl', false),
  ('KM4', 'KMI-TRD Log Exim', false),
  ('KR0', 'KRW-HRGA', false),
  ('KR1', 'KRW-NTRD Pur', false),
  ('KR2', 'KRW-NTRD Log', false),
  ('KR3', 'KRW-TRD Log Locl', false),
  ('KR4', 'KRW-TRD Log Exim', false),
  ('L1A', 'M. Zuhri', false),
  ('L1B', 'Dolly Sarumpaet', false),
  ('L1C', 'Yunita Nandasari', false),
  ('L2A', 'Hermando', false),
  ('L2B', 'Jefriko Saragih', false),
  ('L2C', 'Mochtar', false),
  ('L2D', 'Lyly Yuliane', false),
  ('L3A', 'Heriawan', false),
  ('L3B', 'Ahmad Irfan', false),
  ('L3C', 'Supian Suri', false),
  ('L4A', 'Inactive-Marrdiana', false),
  ('L4B', 'Ratna Sari', false),
  ('L4C', 'Cris Carles', false),
  ('L4D', 'Ali Mahfudh', false),
  ('LG0', 'LGB-HRGA', false),
  ('LG1', 'LGB-NTRD Pur', false),
  ('LG2', 'LGB-NTRD Log', false),
  ('LG3', 'LGB-TRD Log Locl', false),
  ('LG4', 'LGB-TRD Log Exim', false),
  ('LL1', 'LEGAL LICENSE', false),
  ('MK1', 'MKE-HRGA', false),
  ('MK2', 'MKE-NTRD Pur/Log', false),
  ('MK3', 'MKE-TRD Log Locl', false),
  ('MK4', 'MKE-TRD Log Exim', false),
  ('MS1', 'HO-MIS', true),
  ('OP1', 'STORE OPS UNIT', false),
  ('OP2', 'NTRD-HO-OPS-2', true),
  ('OP3', 'NTRD-HO-OPS-3', true),
  ('OP4', 'NTRD-HO-OPS-4', true),
  ('P00', 'Johny Rusli', false),
  ('P01', 'Dedi Kurniadi', false),
  ('P02', 'Destyarina Ayu', false),
  ('P04', 'Fransisca Sekar', false),
  ('P05', 'Dyah Purnomosari', false),
  ('P06', 'Serena', false),
  ('P07', 'Danang Tri W', false),
  ('P08', 'Batildis Irma', false),
  ('P10', 'Syifa Husnul Ramdi', false),
  ('P11', 'Ninik Hemin Felani', false),
  ('P12', 'Leonardy Sunardian', false),
  ('P13', 'Michael Chandra', false),
  ('P15', 'Derry Nansiswa', false),
  ('P16', 'Sefti Muharlinda', false),
  ('P17', 'Restiyana Dningrum', false),
  ('P18', 'KURNIAWATI', false),
  ('P19', 'Eva Maria B', false),
  ('P20', 'Sujatmoko', false),
  ('P21', 'Nathalia Kevina', false),
  ('P22', 'Nadia Ulfiani', false),
  ('P23', 'Primadita Kurnia', false),
  ('P24', 'Agustinus Wirawan', false),
  ('P25', 'Ivarera', false),
  ('P27', 'Riana Manalu', false),
  ('P28', 'Badriyasin', false),
  ('P29', 'Ranie Pramithasari', false),
  ('P30', 'Joenathan W.', false),
  ('P31', 'Diana Setia Wati', false),
  ('P32', 'Maulana Ibrahim', false),
  ('P33', 'Tia Maulida', false),
  ('P34', 'Lisbeth Berutu', false),
  ('P35', 'Sundoro Bayu', false),
  ('P36', 'Yohannes', false),
  ('P40', 'Dwi Sudistira', false),
  ('P41', 'Iklil Azizah Nur', false),
  ('P42', 'Winaldo', false),
  ('P43', 'Elizabeth Austina', false),
  ('P44', 'Bryan Geraldy Guna', false),
  ('P45', 'Dheni Budi', false),
  ('P47', 'Gabrielie Alicia', false),
  ('P48', 'Nadhifa Augiselvia', false),
  ('P49', 'Evelyn Wijaya', false),
  ('P50', 'Selvie Marina', false),
  ('P51', 'Caroline K Suryadi', false),
  ('P52', 'Fadhillah N Fauzi', false),
  ('P53', 'Dedrick David', false),
  ('P54', 'Jovan Firdy', false),
  ('P55', 'Agung Sitepu', false),
  ('P56', 'Billy Tirta', false),
  ('P57', 'Lysa Febriyantie', false),
  ('P58', 'Petrus Nong Robi', false),
  ('P59', 'Dwi Nur Oktaviani', false),
  ('P60', 'Justin Oliver', false),
  ('P99', 'Document Migrate', false),
  ('PB0', 'PLB-HRGA', false),
  ('PB1', 'PLB-NTRD Pur', false),
  ('PB2', 'PLB-NTRD Log', false),
  ('PB3', 'PLB-TRD Log Locl', false),
  ('PB4', 'PLB-TRD Log Exim', false),
  ('PBT', 'Purchasing BTP', false),
  ('PL0', 'PUL RO-HRGA', false),
  ('PL1', 'PUL RO-NTRDPur', false),
  ('PL2', 'Pul RO-NTRDLog', false),
  ('PP0', 'PYP-HRGA', false),
  ('PP1', 'PYP-NTRD Pur', false),
  ('PP2', 'PYP-NTRD Log', false),
  ('PP3', 'PYP-TRD Log Locl', false),
  ('PP4', 'PYP-TRD Log Exim', false),
  ('PPC', 'Okto Darmawan', false),
  ('PR1', 'STORE PROJ UNIT', false),
  ('PR2', 'NTRD-HO-PROJECT-2', true),
  ('PR3', 'NTRD-HO-PROJECT-3', true),
  ('PR4', 'NTRD-HO-PROJECT-4', true),
  ('PT1', 'PTK RO-HRGA', false),
  ('PT2', 'PTK RO-NTRDPur/Log', false),
  ('R01', 'Rusli', false),
  ('R04', 'Ahmad Rusdi', false),
  ('R05', 'Herawati', false),
  ('R06', 'Fauzan Akbar', false),
  ('R07', 'Dikki Givoni', false),
  ('R08', 'Herma Aguslianto', false),
  ('R09', 'Yusnan', false),
  ('R10', 'Hesi Liana Sari', false),
  ('R11', 'Bujang Saputra', false),
  ('SA0', 'SAL-HRGA', false),
  ('SA1', 'SAL-NTRD Pur', false),
  ('SA2', 'SAL-NTRD Log', false),
  ('SA3', 'SAL-TRD Log Locl', false),
  ('SA4', 'SAL-TRD Log Exim', false),
  ('SD0', 'SDA-HRGA', false),
  ('SD1', 'SDA-NTRD Pur', false),
  ('SD2', 'SDA-NTRD Log', false),
  ('SD3', 'SDA-TRD Log Locl', false),
  ('SD4', 'SDA-TRD Log Exim', false),
  ('SI0', 'SIN-HRGA', false),
  ('SI1', 'SIN-NTRD Pur', false),
  ('SI2', 'SIN-NTRD Log', false),
  ('SI3', 'SIN-TRD Log Locl', false),
  ('SI4', 'SIN-TRD Log Exim', false),
  ('SM0', 'SMD-RO HRGA', false),
  ('SM1', 'SMD-RO-NTRDPur', false),
  ('SM2', 'SMD-RO-NTRDLog', false),
  ('T01', 'TRD-HO Trd Dws', false),
  ('T02', 'TRD-HO Trd Ups', false),
  ('T03', 'TRD-HO Sls Log Ex', false),
  ('T04', 'TRD-HO Sls Log Loc', false),
  ('T05', 'TRD-HO PurLog Loc', false),
  ('T06', 'TRD-HO PurLog Impt', false),
  ('T07', 'TRD-HO Log TC', false),
  ('T0A', 'Lian Pongoh', false),
  ('T0B', 'Garry Wilian', false),
  ('T0C', 'Jesslyn Jovian', false),
  ('T0D', 'Elfrida Hana P', false),
  ('T0E', 'Stefany Patricia M', false),
  ('T0F', 'Leonardo Setiawan', false),
  ('T0G', 'Alvin Margono', false),
  ('T0H', 'Suyanti', false),
  ('T0I', 'Jonathan Kusuma', false),
  ('T0J', 'Ani Ernawati', false),
  ('T0K', 'Jessyca Ang', false),
  ('T0L', 'Fanny Chen', false),
  ('T0M', 'Sandrianna Ozora', false),
  ('T0N', 'Irma Sri Utami', false),
  ('T0O', 'Edwin Santoso', false),
  ('T0P', 'Karin Sela Suteja', false),
  ('T0Q', 'Novi Christin', false),
  ('T0R', 'Leonardo Setiawan', false),
  ('T0S', 'Edward Chong', false),
  ('T0T', 'Hartatik', false),
  ('T0U', 'Jackie Lee', false),
  ('T0V', 'Hy Tang', false),
  ('T0W', 'Angella Metta Liun', false),
  ('T0X', 'Silvia Kosasih', false),
  ('T1A', 'Rafi Lubis', false),
  ('T1B', 'Alfred Jonan', false),
  ('T1C', 'Firas Harahap', false),
  ('T1D', 'Angella Liunardy', false),
  ('T1E', 'Faryn Deandra', false),
  ('T1F', 'Jocelyn', false),
  ('T1G', 'Evan Ang', false),
  ('T1H', 'Engel Dyta', false),
  ('T50', 'TRD-UNIT MALAY', false),
  ('T99', 'TRD-UNIT INDO', false),
  ('TB0', 'TJB-HRGA', false),
  ('TB1', 'TJB-NTRD Pur', false),
  ('TB2', 'TJB-NTRD Log', false),
  ('TB3', 'TJB-TRD Log Locl', false),
  ('TB4', 'TJB-TRD Log Exim', false),
  ('TG0', 'TGR-HRGA', false),
  ('TG1', 'TGR-NTRD Pur', false),
  ('TG2', 'TGR-NTRD Log', false),
  ('TG3', 'TGR-TRD Log Locl', false),
  ('TG4', 'TGR-TRD Log Exim', false),
  ('TL0', 'TJL-HRGA', false),
  ('TL1', 'TJL-NTRD Pur', false),
  ('TL2', 'TJL-NTRD Log', false),
  ('TL3', 'TJL-TRD Log Locl', false),
  ('TL4', 'TJL-TRD Log Exim', false),
  ('TM0', 'TJM-HRGA', false),
  ('TM1', 'TJM-NTRD Pur', false),
  ('TM2', 'TJM-NTRD Log', false),
  ('TM3', 'TJM-TRD Log Locl', false),
  ('TM4', 'TJM-TRD Log Exim', false),
  ('TP0', 'TJP-HRGA', false),
  ('TP1', 'TJP-NTRD Pur', false),
  ('TP2', 'TJP-NTRD Log', false),
  ('TP3', 'TJP-TRD Log Locl', false)

ON CONFLICT (code) DO UPDATE
  SET description = EXCLUDED.description, is_ho = EXCLUDED.is_ho;
