/**
 * Plant -> Area roll-up, from the business's Master_Area.xlsx (embedded in the
 * v1 dashboard; 131 plants / 26 areas). The Assets drop has no Master_Area
 * feed, so this ships as reference data exactly as v1 shipped it, and fills
 * core.dim_plant.area on every ingest. Plants absent here keep a NULL area
 * and fall back to their own code in area charts.
 */
export const PLANT_AREA: Record<string, string> = {
  'AS00': 'HO',
  'BM00': 'HO',
  'BN00': 'HO',
  'BN10': 'HO',
  'CD00': 'HO',
  'CD10': 'HO',
  'CD21': 'Cisadane',
  'CD22': 'Cisadane',
  'CD2A': 'Cisadane',
  'CS00': 'HO',
  'EO00': 'HO',
  'EO10': 'HO',
  'EO21': 'EOP Tj Morawa',
  'EO22': 'EOP Tj Morawa',
  'EO2A': 'EOP Tj Morawa',
  'EO92': 'Bulking Belawan',
  'EU00': 'HO',
  'EU10': 'HO',
  'EU21': 'Bulking Lubuk Gaung',
  'EU22': 'Bontang',
  'EU23': 'Tanjung Pura',
  'EU24': 'Bulking Kumai',
  'EU25': 'Bulking Palembang',
  'EU26': 'Bulking Batam',
  'EU27': 'Bulking Sintang',
  'EU28': 'Merauke',
  'EU29': 'Bagendang',
  'EU2B': 'Bontang',
  'EU2C': 'Tanjung Pura',
  'EU2D': 'Bontang',
  'EU2E': 'Tanjung Pura',
  'EU2Y': 'Paya Pasir',
  'EU2Z': 'Bekasi',
  'EU31': 'Boven Digoel',
  'EU3A': 'Boven Digoel',
  'EU4B': 'Bontang',
  'EU4C': 'Tanjung Pura',
  'EU4D': 'Bontang',
  'EU4E': 'Tanjung Pura',
  'EU51': 'Bulking Lubuk Gaung',
  'EU52': 'Bontang',
  'EU53': 'Tanjung Pura',
  'EU54': 'Bulking Kumai',
  'EU55': 'Bulking Palembang',
  'EU62': 'Bontang',
  'EU71': 'Bulking Lubuk Gaung',
  'EU72': 'Bontang',
  'EU73': 'Tanjung Pura',
  'EU90': 'HO',
  'EU91': 'Bulking Lubuk Gaung',
  'EU92': 'Bontang',
  'EU93': 'Tanjung Pura',
  'EU94': 'Bulking Kumai',
  'EU95': 'Bulking Palembang',
  'EU96': 'Bulking Batam',
  'EU9A': 'Bulking Lubuk Gaung',
  'EU9B': 'Bontang',
  'EU9C': 'Tanjung Pura',
  'EU9D': 'Bulking Kumai',
  'EU9E': 'Bulking Palembang',
  'EU74': 'Bulking Kumai',
  'EU75': 'Bulking Palembang',
  'EU76': 'Bulking Batam',
  'EU77': 'Bulking Sintang',
  'EU78': 'Merauke',
  'EU7A': 'Boven Digoel',
  'EU7Y': 'Paya Pasir',
  'EU9Y': 'Paya Pasir',
  'EUL0': 'HO',
  'GM00': 'HO',
  'GM10': 'HO',
  'GM21': 'Port Klang',
  'GM2A': 'Port Klang',
  'JP00': 'HO',
  'JP10': 'HO',
  'JP21': 'Bekasi',
  'JP22': 'Sidoarjo',
  'JP26': 'Gresik',
  'JP27': 'Lubuk Gaung',
  'JPL0': 'HO',
  'MG00': 'HO',
  'MG10': 'HO',
  'MG21': 'Tanjung Pura',
  'ND00': 'HO',
  'ND10': 'HO',
  'ND21': 'Merauke',
  'ND4A': 'Merauke',
  'ND71': 'Merauke',
  'PE00': 'HO',
  'PE10': 'HO',
  'PE21': 'Bayah',
  'PE22': 'Bontang',
  'PE23': 'Salo Palai',
  'PM00': 'HO',
  'PM10': 'HO',
  'PM21': 'Lubuk Gaung',
  'PM90': 'HO',
  'PM91': 'Lubuk Gaung',
  'PS00': 'HO',
  'PS10': 'HO',
  'PS21': 'Bekasi',
  'PS22': 'Bekasi',
  'PS23': 'Karawang',
  'PS2A': 'Karawang',
  'PS2B': 'Karawang',
  'PS4A': 'Karawang',
  'PS4B': 'Karawang',
  'PSL0': 'HO',
  'RB00': 'HO',
  'RB10': 'HO',
  'RB21': 'Tanjung Buton',
  'RI00': 'HO',
  'RI10': 'HO',
  'RI21': 'Bekasi',
  'RIL0': 'HO',
  'SB00': 'HO',
  'SB10': 'HO',
  'SB21': 'Salo Palai',
  'SB22': 'Sintete',
  'SC00': 'HO',
  'SC10': 'HO',
  'SC21': 'Bulking Batam',
  'SC22': 'Bulking Lubuk Gaung',
  'SC4A': 'Bulking Batam',
  'SC4B': 'Bulking Lubuk Gaung',
  'SS00': 'HO',
  'TP00': 'HO',
  'TP10': 'HO',
  'TP21': 'Tj Langsat',
  'TP2A': 'Tj Langsat',
  'UI00': 'HO',
};
